apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hello-gitops

bases:
  - ../base

images:
- name: hello-gitops
  newName: caiobegotti/hello-gitops
  newTag: latest

resources:
- volumes.yaml
- ingress.yaml
- service.yaml
- deployment.yaml
