---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: hello-gitops-volume-dev
  labels:
    type: local
spec:
  storageClassName: fast
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hello-gitops-volume-dev
spec:
  storageClassName: fast
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
